version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: library_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: library_db
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: library_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://library_user:library_password@mysql:3306/library_db
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
      MYSQL_DB: library_db
      DEBUG: "True"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data:
